Dbohninx update
daos-stack/dtcmp pull request #3
Opened 2021-01-19 18:06 UTC by daltonbohning

Update to version 1.1.1, including patch.
Update packaging to latest.

2021-02-04 18:26 UTC, brianjmurrell requested changes

2021-02-04 18:26 UTC, brianjmurrell commented on dtcmp.spec
> +Release:	2%{?dist}
```suggestion
Release:	1%{?dist}
```

2021-02-04 18:26 UTC, brianjmurrell commented on dtcmp.spec
> +* Tue Jan 19 2021 Dalton A. Bohning <daltonx.bohning@intel.com> - 1.1.1-2
```suggestion
* Tue Jan 19 2021 Dalton A. Bohning <daltonx.bohning@intel.com> - 1.1.1-1
```

2021-02-08 15:27 UTC, daltonbohning commented
Order of dependencies:
lwgrp dot version update - https://github.com/daos-stack/lwgrp/pull/3
dtcmp dot  version update - (depends on lwgrp) This PR
mpifileutils minor version update - (depends on dtcmp) https://github.com/daos-stack/mpifileutils-pkg/pull/9

2021-02-08 19:21 UTC, brianjmurrell approved these changes

2021-02-08 19:21 UTC, merged